apiVersion: fortio.verf.io/v1alpha1
kind: TestRun
metadata:
  name: verfio
spec:
  curl:
  - order: "10"
    url: "https://verf.io"
  load:
  - order: "20"
    url: "https://verf.io"
    duration: 10s
  - order: "30"
    url: "https://www.verf.io"
    duration: 1m
  - order: "40"
    url: "https://www.verf.io"
    duration: 10m
  