apiVersion: v1
data:
  payload: |
    StartTest
    {"test":"data"}
    EndTest
kind: ConfigMap
metadata:
  name: verfio-test
---
apiVersion: fortio.verf.io/v1alpha1
kind: CurlTest
metadata:
  name: verfio
spec:
  url: "https://verf.io"
  lookForString: "VERF.IO"
  method: "POST"
  payloadFile: "payload"
  payloadConfigMap: verfio-test