apiVersion: fortio.verf.io/v1alpha1
kind: TestRun
metadata:
  name: verfio
spec:
  curl:
  - order: "10"
    url: "https://verf.io"
  - order: "15"
    url: "https://verf.io"
    method: "POST"
  load:
  - order: "20"
    url: "https://verf.io"
    duration: 10s
  - order: "30"
    url: "https://www.verf.io"
    duration: 30s
