apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fortio-operator
  template:
    metadata:
      labels:
        name: fortio-operator
    spec:
      serviceAccountName: fortio-operator
      containers:
        - name: fortio-operator
          # Replace this with the built image name
          image: ochorny/fortio-operator
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - fortio-operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "fortio-operator"
